package internal_test

import (
	"context"
	"encoding/json"
	"io"
	"log/slog"
	"sync"
	"testing"
	"time"

	"github.com/redis/go-redis/v9"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	"github.com/kochan4php/go-platform-starter/internal/platform"
	"github.com/kochan4php/go-platform-starter/internal/testutil"
	internal "github.com/kochan4php/go-platform-starter/services/auth/internal"
)

// --- test scaffolding -------------------------------------------------------

type capturedPublisher struct {
	events []capturedEvent
}

type capturedEvent struct {
	Stream  string
	Event   string
	Payload map[string]string
}

func (p *capturedPublisher) Publish(_ context.Context, stream, event string, payload any) error {
	raw, _ := json.Marshal(payload)
	m := map[string]string{}
	_ = json.Unmarshal(raw, &m)
	p.events = append(p.events, capturedEvent{Stream: stream, Event: event, Payload: m})
	return nil
}

func (p *capturedPublisher) lastPayload(stream, event string) map[string]string {
	for i := len(p.events) - 1; i >= 0; i-- {
		if p.events[i].Stream == stream && p.events[i].Event == event {
			return p.events[i].Payload
		}
	}
	return nil
}

type fixture struct {
	svc *internal.Service
	pub *capturedPublisher
	rdb *redis.Client
	db  *gorm.DB
}

func newFixture(t *testing.T) *fixture {
	t.Helper()
	dsn := testutil.StartPostgres(t)
	addr := testutil.StartRedis(t)
	log := slog.New(slog.NewTextHandler(io.Discard, nil))

	if err := retryUntil(func() error { return internal.MigrateUp(dsn) }, 20*time.Second); err != nil {
		t.Fatalf("migrate: %v", err)
	}

	// The identity row now lives in users.users (owned by the users service).
	// Auth tests only need a compatible shape, so create it inline rather than
	// importing another service's migrations (depguard boundary).
	ddl := `
		CREATE SCHEMA IF NOT EXISTS users;
		CREATE SCHEMA IF NOT EXISTS rbac;
		CREATE TABLE IF NOT EXISTS rbac.user_versions (user_id BIGINT PRIMARY KEY, ver BIGINT NOT NULL DEFAULT 0);
		CREATE TABLE IF NOT EXISTS users.users (
			id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
			email                 TEXT        NOT NULL,
			password_hash         TEXT        NOT NULL,
			password_history      TEXT[]      NOT NULL DEFAULT '{}',
			mfa_secret_enc        TEXT        NOT NULL DEFAULT '',
			mfa_enabled           BOOLEAN     NOT NULL DEFAULT false,
			deleted_at            TIMESTAMPTZ,
			status                TEXT        NOT NULL DEFAULT 'active',
			failed_login_attempts INT         NOT NULL DEFAULT 0,
			locked_until          TIMESTAMPTZ,
			display_name          TEXT        NOT NULL DEFAULT '',
			avatar_url            TEXT        NOT NULL DEFAULT '',
			last_login_at         TIMESTAMPTZ,
			last_login_ip         TEXT        NOT NULL DEFAULT '',
			last_login_user_agent TEXT        NOT NULL DEFAULT '',
			created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
			updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
		);`
	db, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger: platform.NewGormLogger(log, time.Minute),
	})
	if err != nil {
		t.Fatalf("gorm: %v", err)
	}
	if err := db.Exec(ddl).Error; err != nil {
		t.Fatalf("users ddl: %v", err)
	}

	rdb := redis.NewClient(&redis.Options{Addr: addr})
	t.Cleanup(func() { _ = rdb.Close() })

	cfg := internal.Config{
		AccessTokenSecret:   "test-secret-at-least-16ch!",
		AccessTTLMinutes:    30,
		RefreshTTLDays:      7,
		BcryptCost:          4,
		LoginMaxAttempts:    3,
		LoginLockMinutes:    15,
		ResetTTLMinutes:     15,
		AppPublicURL:        "http://127.0.0.1:5173",
		RateGlobalPerMinute: 1000,
		RateStrictPerMinute: 1000,
		RefreshGrace:        2 * time.Second,
		MaxActiveSessions:   2,
	}
	pub := &capturedPublisher{}
	return &fixture{svc: internal.NewService(db, rdb, log, cfg, pub), pub: pub, rdb: rdb, db: db}
}

func mustRegister(t *testing.T, f *fixture, email string) {
	t.Helper()
	if _, err := f.svc.Register(context.Background(), email, "password-123"); err != nil {
		t.Fatalf("register %s: %v", email, err)
	}
}

func retryUntil(fn func() error, within time.Duration) error {
	deadline := time.Now().Add(within)
	for {
		err := fn()
		if err == nil {
			return nil
		}
		if !time.Now().After(deadline) {
			time.Sleep(500 * time.Millisecond)
			continue
		}
		return err
	}
}

func resetTokenFromMail(t *testing.T, f *fixture) string {
	t.Helper()
	payload := f.pub.lastPayload(internal.StreamMail, internal.EventSend)
	if payload == nil {
		t.Fatal("no mail job published")
	}
	var html struct {
		Html string `json:"html"`
	}
	if err := json.Unmarshal([]byte(payload["html"]), &html); err == nil && html.Html != "" {
		t.Fatal("unexpected html encoding")
	}
	link := payload["html"]
	i := indexOf(link, "token=")
	if i < 0 {
		t.Fatalf("no token in mail html: %s", link)
	}
	token := link[i+len("token="):]
	if end := indexOf(token, "\""); end >= 0 {
		token = token[:end]
	}
	return token
}

func indexOf(s, sub string) int {
	for i := 0; i+len(sub) <= len(s); i++ {
		if s[i:i+len(sub)] == sub {
			return i
		}
	}
	return -1
}

// --- tests ------------------------------------------------------------------

func TestAdminStateAndPasswordConfirmation(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	user, err := f.svc.Register(ctx, "state@example.local", "password-123")
	if err != nil {
		t.Fatal(err)
	}
	if err := f.svc.ConfirmPassword(ctx, user.ID, "password-123"); err != nil {
		t.Fatalf("confirm valid password: %v", err)
	}
	if err := f.svc.ConfirmPassword(ctx, user.ID, "wrong-password"); err == nil {
		t.Fatal("wrong password was accepted")
	}
	inactive := "inactive"
	if err := f.svc.SetUserState(ctx, user.ID, &inactive, nil); err != nil {
		t.Fatalf("deactivate: %v", err)
	}
	if _, err := f.svc.Login(ctx, user.Email, "password-123", "test", "127.0.0.1"); err == nil {
		t.Fatal("inactive user logged in")
	}
	active := "active"
	unlocked := false
	if err := f.svc.SetUserState(ctx, user.ID, &active, &unlocked); err != nil {
		t.Fatalf("activate: %v", err)
	}
	if _, err := f.svc.Login(ctx, user.Email, "password-123", "test", "127.0.0.1"); err != nil {
		t.Fatalf("active user login: %v", err)
	}
}

func TestRegisterEmitsUserCreatedAndRejectsDuplicates(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()

	if _, err := f.svc.Register(ctx, "Ada@example.local", "password-123", "Ada Lovelace"); err != nil {
		t.Fatal(err)
	}

	ev := f.pub.lastPayload(internal.StreamUsers, internal.EventCreated)
	if ev == nil || ev["email"] != "ada@example.local" || ev["sub"] == "" || ev["display_name"] != "Ada Lovelace" {
		t.Fatalf("user.created payload wrong: %+v", ev)
	}

	_, err := f.svc.Register(ctx, "ada@example.local", "password-123")
	if err == nil {
		t.Fatal("duplicate register must fail")
	}
	appErr, ok := err.(*platform.AppError)
	if !ok || appErr.Status != 409 {
		t.Fatalf("want 409 conflict, got %#v", err)
	}
}

func TestLoginIsUniformForUnknownWrongAndLocked(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	mustRegister(t, f, "bob@example.local")

	cases := []struct{ name, email, pw string }{
		{"unknown user", "nobody@example.local", "whatever-123"},
		{"wrong password", "bob@example.local", "wrong-password"},
	}
	var firstErrBody string
	for _, tc := range cases {
		_, err := f.svc.Login(ctx, tc.email, tc.pw, "test-agent", "10.0.0.1")
		if err == nil {
			t.Fatalf("%s should fail", tc.name)
		}
		body := err.Error()
		if firstErrBody == "" {
			firstErrBody = body
			continue
		}
		if body != firstErrBody {
			t.Fatalf("%s response not uniform:\n%s\n%s", tc.name, body, firstErrBody)
		}
	}

	for i := 0; i < 3; i++ {
		_, _ = f.svc.Login(ctx, "bob@example.local", "wrong-password", "a", "b")
	}
	_, err := f.svc.Login(ctx, "bob@example.local", "password-123", "a", "b")
	if err == nil {
		t.Fatal("locked account with correct password must still fail")
	}
	appErr := err.(*platform.AppError)
	if appErr.Status != 401 || appErr.Message != "invalid_credentials" {
		t.Fatalf("locked response must stay uniform 401 invalid_credentials, got %#v", appErr)
	}
}

func TestRefreshRotationAndReuseDetection(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	mustRegister(t, f, "carol@example.local")

	login, err := f.svc.Login(ctx, "carol@example.local", "password-123", "ua", "ip")
	if err != nil {
		t.Fatalf("login: %v", err)
	}

	res1, err := f.svc.Refresh(ctx, login.RefreshCookie)
	if err != nil {
		t.Fatalf("first refresh: %v", err)
	}
	if res1.RefreshCookie == "" || res1.AccessToken == "" || res1.FamilyID != login.FamilyID {
		t.Fatalf("rotated result incomplete: %+v", res1)
	}

	grace, err := f.svc.Refresh(ctx, login.RefreshCookie)
	if err != nil || grace.RefreshCookie != res1.RefreshCookie {
		t.Fatal("old refresh token must return the same rotation inside the grace window")
	}
	time.Sleep(2100 * time.Millisecond)

	if _, err := f.svc.Refresh(ctx, login.RefreshCookie); err == nil {
		t.Fatal("replayed old refresh token after grace must fail")
	}
	if _, err := f.svc.Refresh(ctx, res1.RefreshCookie); err == nil {
		t.Fatal("refresh after family kill must fail even with the newest token")
	}
}

func TestConcurrentRefreshSharesOneRotation(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	mustRegister(t, f, "parallel-refresh@example.local")
	login, err := f.svc.Login(ctx, "parallel-refresh@example.local", "password-123", "ua", "ip", "device-a")
	if err != nil {
		t.Fatal(err)
	}

	start := make(chan struct{})
	results := make(chan *internal.AuthResult, 2)
	errs := make(chan error, 2)
	var wg sync.WaitGroup
	for range 2 {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			result, refreshErr := f.svc.Refresh(ctx, login.RefreshCookie, "device-a")
			results <- result
			errs <- refreshErr
		}()
	}
	close(start)
	wg.Wait()
	close(results)
	close(errs)
	for refreshErr := range errs {
		if refreshErr != nil {
			t.Fatalf("concurrent refresh failed: %v", refreshErr)
		}
	}
	var cookie string
	for result := range results {
		if result == nil || result.RefreshCookie == "" {
			t.Fatal("concurrent refresh returned an empty rotation")
		}
		if cookie == "" {
			cookie = result.RefreshCookie
		} else if result.RefreshCookie != cookie {
			t.Fatal("concurrent refreshes did not share the same rotation")
		}
	}
}

func TestDeviceBindingAndConcurrentSessionLimit(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	user, err := f.svc.Register(ctx, "device@example.local", "password-123")
	if err != nil {
		t.Fatal(err)
	}
	first, err := f.svc.Login(ctx, user.Email, "password-123", "ua", "ip", "device-a")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := f.svc.Refresh(ctx, first.RefreshCookie, "device-b"); err == nil {
		t.Fatal("refresh token accepted from another device")
	}
	_, _ = f.svc.Login(ctx, user.Email, "password-123", "ua", "ip", "device-b")
	_, _ = f.svc.Login(ctx, user.Email, "password-123", "ua", "ip", "device-c")
	sessions, err := f.svc.ListSessions(ctx, user.ID, "")
	if err != nil || len(sessions) != 2 {
		t.Fatalf("active sessions = %d, err=%v", len(sessions), err)
	}
}

func TestLogoutRevokesSession(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	mustRegister(t, f, "dave@example.local")

	login, _ := f.svc.Login(ctx, "dave@example.local", "password-123", "ua", "ip")
	if _, err := f.svc.Refresh(ctx, login.RefreshCookie); err != nil {
		t.Fatalf("pre-logout refresh: %v", err)
	}
	if err := f.svc.Logout(ctx, login.RefreshCookie); err != nil {
		t.Fatalf("logout: %v", err)
	}
	if _, err := f.svc.Refresh(ctx, login.RefreshCookie); err == nil {
		t.Fatal("refresh after logout must fail")
	}
}

func TestForgotIsUniformAndResetIsSingleUseAndWipesSessions(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	mustRegister(t, f, "erin@example.local")

	if err := f.svc.Forgot(ctx, "ghost@example.local"); err != nil {
		t.Fatalf("forgot unknown email must be uniform success, got %v", err)
	}
	if tok := f.pub.lastPayload(internal.StreamMail, internal.EventSend); tok != nil {
		t.Fatal("unknown account must not enqueue any mail")
	}

	if err := f.svc.Forgot(ctx, "erin@example.local"); err != nil {
		t.Fatalf("forgot: %v", err)
	}
	token := resetTokenFromMail(t, f)
	if err := f.svc.ValidateReset(ctx, token); err != nil {
		t.Fatalf("preflight must accept an unused reset token: %v", err)
	}
	if err := f.svc.ValidateReset(ctx, "not-a-token"); err == nil {
		t.Fatal("preflight must reject an invalid reset token")
	}

	if _, err := f.svc.Login(ctx, "erin@example.local", "password-123", "ua", "ip"); err != nil {
		t.Fatalf("login before reset: %v", err)
	}
	if err := f.svc.Reset(ctx, token, "new-password-456"); err != nil {
		t.Fatalf("reset: %v", err)
	}

	if _, err := f.svc.Login(ctx, "erin@example.local", "password-123", "ua", "ip"); err == nil {
		t.Fatal("old password must stop working after reset")
	}
	if _, err := f.svc.Login(ctx, "erin@example.local", "new-password-456", "ua", "ip"); err != nil {
		t.Fatalf("new password must work: %v", err)
	}
	if err := f.svc.Reset(ctx, token, "again-password-789"); err == nil {
		t.Fatal("replayed reset token must fail (single-use)")
	}
	if err := f.svc.ValidateReset(ctx, token); err == nil {
		t.Fatal("preflight must reject a consumed reset token")
	}
}

func TestEnsureBootstrapAdminResetsConflictAndRevokesSessions(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	const email = "bootstrap@example.local"
	if err := f.svc.EnsureBootstrapAdmin(ctx, "1", email, "initial-password-123"); err != nil {
		t.Fatalf("initial bootstrap: %v", err)
	}
	login, err := f.svc.Login(ctx, email, "initial-password-123", "seed-agent", "127.0.0.1")
	if err != nil {
		t.Fatalf("initial login: %v", err)
	}
	if err := f.svc.EnsureBootstrapAdmin(ctx, "1", email, "replacement-password-456"); err != nil {
		t.Fatalf("conflict reset: %v", err)
	}
	if _, err := f.svc.Refresh(ctx, login.RefreshCookie); err == nil {
		t.Fatal("bootstrap reset did not revoke the existing session")
	}
	if _, err := f.svc.Login(ctx, email, "initial-password-123", "seed-agent", "127.0.0.1"); err == nil {
		t.Fatal("old bootstrap password still works")
	}
	if _, err := f.svc.Login(ctx, email, "replacement-password-456", "seed-agent", "127.0.0.1"); err != nil {
		t.Fatalf("replacement password login: %v", err)
	}
}

func TestAdminPasswordChangeNotFoundRevokesSessionsAndAudits(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	if err := f.svc.SetPasswordByID(ctx, 999999, "replacement-password-456"); err == nil {
		t.Fatal("unknown user password change succeeded")
	}
	user, err := f.svc.Register(ctx, "managed@example.local", "initial-password-123")
	if err != nil {
		t.Fatal(err)
	}
	login, err := f.svc.Login(ctx, user.Email, "initial-password-123", "Chrome/140", "203.0.113.7")
	if err != nil {
		t.Fatal(err)
	}
	if err := f.svc.SetPasswordByID(ctx, user.ID, "replacement-password-456"); err != nil {
		t.Fatalf("admin password change: %v", err)
	}
	if _, err := f.svc.Refresh(ctx, login.RefreshCookie); err == nil {
		t.Fatal("admin password change did not revoke sessions")
	}
	audit := f.pub.lastPayload(platform.StreamAudit, "audit.entry")
	if audit == nil || audit["action"] != "password.admin_changed" {
		t.Fatalf("password change audit missing: %#v", audit)
	}
}

func TestLoginPersistsOriginalTelemetry(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	user, err := f.svc.Register(ctx, "telemetry@example.local", "initial-password-123")
	if err != nil {
		t.Fatal(err)
	}
	if _, err := f.svc.Login(ctx, user.Email, "initial-password-123", "Firefox/141 Linux", "198.51.100.9"); err != nil {
		t.Fatal(err)
	}
	var stored internal.User
	if err := f.db.First(&stored, user.ID).Error; err != nil {
		t.Fatal(err)
	}
	if stored.LastLoginAt == nil || stored.LastLoginIP != "198.51.100.9" || stored.LastLoginUserAgent != "Firefox/141 Linux" {
		t.Fatalf("login telemetry = %#v", stored)
	}
}

func TestTokenIntrospectionChecksCurrentLifecycleState(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	user, err := f.svc.Register(ctx, "introspection@example.local", "initial-password-123")
	if err != nil {
		t.Fatal(err)
	}
	login, err := f.svc.Login(ctx, user.Email, "initial-password-123", "test", "127.0.0.1")
	if err != nil {
		t.Fatal(err)
	}
	result, err := f.svc.IntrospectToken(ctx, login.AccessToken)
	if err != nil || !result.Active || result.Sub == "" {
		t.Fatalf("active introspection = %#v err=%v", result, err)
	}
	inactive := "inactive"
	if err := f.svc.SetUserState(ctx, user.ID, &inactive, nil); err != nil {
		t.Fatal(err)
	}
	result, err = f.svc.IntrospectToken(ctx, login.AccessToken)
	if err != nil || result.Active {
		t.Fatalf("inactive introspection = %#v err=%v", result, err)
	}
	result, err = f.svc.IntrospectToken(ctx, "invalid")
	if err != nil || result.Active {
		t.Fatalf("invalid introspection = %#v err=%v", result, err)
	}
}

func TestConcurrentRegisterSameEmailHasSingleWinner(t *testing.T) {
	f := newFixture(t)
	ctx := context.Background()
	start := make(chan struct{})
	errs := make(chan error, 2)
	var wg sync.WaitGroup
	for range 2 {
		wg.Add(1)
		go func() {
			defer wg.Done()
			<-start
			_, err := f.svc.Register(ctx, "race@example.local", "initial-password-123")
			errs <- err
		}()
	}
	close(start)
	wg.Wait()
	close(errs)
	successes := 0
	for err := range errs {
		if err == nil {
			successes++
		}
	}
	if successes != 1 {
		t.Fatalf("successful concurrent registrations = %d, want 1", successes)
	}
}
