SET lock_timeout = '5s';
SET statement_timeout = '5min';

CREATE TABLE IF NOT EXISTS users.product_records (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind          TEXT        NOT NULL,
    owner_id      BIGINT      NOT NULL DEFAULT 0,
    subject_id    BIGINT,
    name          TEXT        NOT NULL DEFAULT '',
    status        TEXT        NOT NULL DEFAULT 'active',
    payload       JSONB       NOT NULL DEFAULT '{}'::jsonb,
    secret_digest TEXT        NOT NULL DEFAULT '',
    expires_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT product_records_kind_check CHECK (kind IN (
        'notification', 'invitation', 'access_request', 'delegation',
        'api_key', 'webhook', 'scheduled_report', 'saved_view',
        'role_template', 'compliance_report', 'branding', 'domain',
        'billing_usage', 'broadcast', 'chat_message', 'onboarding',
        'retention', 'consumer_quota', 'email_change', 'account_deletion'
    )),
    CONSTRAINT product_records_name_length CHECK (length(name) <= 200),
    CONSTRAINT product_records_status_length CHECK (length(status) <= 40),
    CONSTRAINT product_records_payload_size CHECK (pg_column_size(payload) <= 65536)
);

CREATE INDEX IF NOT EXISTS product_records_owner_kind_created_idx
    ON users.product_records (owner_id, kind, created_at DESC);
CREATE INDEX IF NOT EXISTS product_records_kind_status_created_idx
    ON users.product_records (kind, status, created_at DESC);
CREATE INDEX IF NOT EXISTS product_records_subject_active_idx
    ON users.product_records (subject_id, kind, expires_at)
    WHERE status = 'active';
CREATE UNIQUE INDEX IF NOT EXISTS product_records_deployment_singleton_idx
    ON users.product_records (kind)
    WHERE kind IN ('branding', 'domain', 'retention');

COMMENT ON TABLE users.product_records IS
    'Typed product workflows and preferences; secrets are one-way digests and payload is size-bounded.';
COMMENT ON COLUMN users.product_records.secret_digest IS
    'HMAC digest only; plaintext invitation and API-key material is returned once.';

INSERT INTO users.product_records (kind, owner_id, name, status, payload)
SELECT 'role_template', 0, seed.name, 'active', seed.payload::jsonb
FROM (VALUES
    ('Viewer', '{"source":"curated","permissions":["user:read:any","role:read:any"]}'),
    ('Operator', '{"source":"curated","permissions":["user:read:any","user:update:any","role:read:any"]}'),
    ('Auditor', '{"source":"curated","permissions":["audit:read:any","user:read:any"]}')
) AS seed(name, payload)
WHERE NOT EXISTS (
    SELECT 1 FROM users.product_records existing
    WHERE existing.kind = 'role_template' AND existing.name = seed.name
);
