-- rollback: services/users/migrations/000005_data_governance.down.sql
SET lock_timeout = '5s';
SET statement_timeout = '5min';

CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- PostgreSQL will not change a referenced column type. Rebuild the two small
-- projections inside this migration; their source rows remain untouched.
DROP MATERIALIZED VIEW IF EXISTS users.registration_daily;
DROP MATERIALIZED VIEW IF EXISTS users.dashboard_stats;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status' AND typnamespace = 'users'::regnamespace) THEN
        CREATE TYPE users.user_status AS ENUM ('active', 'inactive', 'deleted');
    END IF;
END $$;

ALTER TABLE users.users ALTER COLUMN status DROP DEFAULT;
ALTER TABLE users.users ALTER COLUMN status TYPE users.user_status USING status::users.user_status;
ALTER TABLE users.users ALTER COLUMN status SET DEFAULT 'active'::users.user_status;

ALTER TABLE users.users
    ADD COLUMN IF NOT EXISTS created_by BIGINT,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT,
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS email_domain TEXT GENERATED ALWAYS AS (split_part(lower(email), '@', 2)) STORED,
    ADD COLUMN IF NOT EXISTS search_document TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('simple', coalesce(email, '') || ' ' || coalesce(display_name, ''))
    ) STORED,
    ADD CONSTRAINT ck_users_email_format CHECK (email ~* '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
    ADD CONSTRAINT ck_users_failed_login_attempts CHECK (failed_login_attempts >= 0),
    ADD CONSTRAINT ck_users_deleted_state CHECK (
        (status = 'deleted'::users.user_status AND deleted_at IS NOT NULL)
        OR (status <> 'deleted'::users.user_status AND deleted_at IS NULL)
    );

CREATE OR REPLACE FUNCTION users.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users.users
FOR EACH ROW EXECUTE FUNCTION users.set_updated_at();

CREATE TABLE users.change_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  TEXT NOT NULL,
    operation   TEXT NOT NULL,
    row_id      TEXT NOT NULL DEFAULT '',
    old_data    JSONB,
    new_data    JSONB,
    changed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    changed_by  BIGINT,
    CONSTRAINT ck_users_change_log_operation CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE OR REPLACE FUNCTION users.capture_row_change()
RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    secret_columns TEXT[] := ARRAY['password_hash', 'password_history', 'mfa_secret_enc'];
BEGIN
    INSERT INTO users.change_log (table_name, operation, row_id, old_data, new_data, changed_by)
    VALUES (
        TG_TABLE_NAME,
        TG_OP,
        CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END::text,
        CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) - secret_columns END,
        CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) - secret_columns END,
        CASE WHEN TG_OP = 'DELETE' THEN OLD.updated_by ELSE NEW.updated_by END
    );
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_users_change_log
AFTER INSERT OR UPDATE OR DELETE ON users.users
FOR EACH ROW EXECUTE FUNCTION users.capture_row_change();

DROP INDEX IF EXISTS users.users_email_unique;
ALTER SEQUENCE users.users_id_seq CACHE 32;
ALTER SEQUENCE users.change_log_id_seq CACHE 32;

COMMENT ON TABLE users.users IS 'Canonical identity, credentials, lifecycle status, and profile record.';
COMMENT ON COLUMN users.users.id IS 'Database-generated canonical user identifier.';
COMMENT ON COLUMN users.users.email IS 'Normalized login email; active rows are unique case-insensitively.';
COMMENT ON COLUMN users.users.password_hash IS 'Argon2id or bcrypt digest; never returned or copied to change logs.';
COMMENT ON COLUMN users.users.status IS 'Database enum: active, inactive, or deleted.';
COMMENT ON COLUMN users.users.failed_login_attempts IS 'Consecutive failed-login count used for lockout.';
COMMENT ON COLUMN users.users.locked_until IS 'Temporary credential lock expiry.';
COMMENT ON COLUMN users.users.display_name IS 'Human-facing profile name.';
COMMENT ON COLUMN users.users.avatar_url IS 'Validated profile avatar URL or empty.';
COMMENT ON COLUMN users.users.last_login_at IS 'Timestamp of the latest successful login.';
COMMENT ON COLUMN users.users.last_login_ip IS 'Latest successful-login IP text representation.';
COMMENT ON COLUMN users.users.last_login_user_agent IS 'Latest successful-login client user agent.';
COMMENT ON COLUMN users.users.created_at IS 'Database-assigned creation timestamp.';
COMMENT ON COLUMN users.users.updated_at IS 'Database-maintained last modification timestamp.';
COMMENT ON COLUMN users.users.deleted_at IS 'Soft-delete timestamp retained for the configured restore window.';
COMMENT ON COLUMN users.users.created_by IS 'Optional actor user id; intentionally no self-referencing FK.';
COMMENT ON COLUMN users.users.updated_by IS 'Optional actor user id; intentionally no self-referencing FK.';
COMMENT ON COLUMN users.users.metadata IS 'Non-sensitive extensible profile metadata.';
COMMENT ON COLUMN users.users.email_domain IS 'Generated lowercase domain extracted from email.';
COMMENT ON COLUMN users.users.search_document IS 'Generated full-text search document for email and display name.';
COMMENT ON COLUMN users.users.password_history IS 'Recent one-way password digests for reuse prevention.';
COMMENT ON COLUMN users.users.mfa_secret_enc IS 'Application-encrypted MFA seed; never emitted to audit JSON.';
COMMENT ON COLUMN users.users.mfa_enabled IS 'Whether MFA verification is required for login.';
COMMENT ON TABLE users.change_log IS 'Database-level row-change history with credential fields redacted.';
COMMENT ON COLUMN users.change_log.id IS 'Database-generated audit sequence.';
COMMENT ON COLUMN users.change_log.table_name IS 'Changed table within the users schema.';
COMMENT ON COLUMN users.change_log.operation IS 'INSERT, UPDATE, or DELETE.';
COMMENT ON COLUMN users.change_log.row_id IS 'Text representation of the changed primary key.';
COMMENT ON COLUMN users.change_log.old_data IS 'Pre-change JSON with credential material removed.';
COMMENT ON COLUMN users.change_log.new_data IS 'Post-change JSON with credential material removed.';
COMMENT ON COLUMN users.change_log.changed_at IS 'Database timestamp of the mutation.';
COMMENT ON COLUMN users.change_log.changed_by IS 'Optional logical user id responsible for the mutation.';

CREATE MATERIALIZED VIEW users.dashboard_stats AS
SELECT
    1 AS id,
    COUNT(*) FILTER (WHERE deleted_at IS NULL) AS total,
    COUNT(*) FILTER (WHERE deleted_at IS NULL AND status = 'active') AS active,
    COUNT(*) FILTER (WHERE deleted_at IS NULL AND status = 'inactive') AS inactive,
    now() AS refreshed_at
FROM users.users;
CREATE UNIQUE INDEX dashboard_stats_id_unique ON users.dashboard_stats (id);
COMMENT ON COLUMN users.dashboard_stats.id IS 'Singleton materialized-view key.';
COMMENT ON COLUMN users.dashboard_stats.total IS 'Current non-deleted user count.';
COMMENT ON COLUMN users.dashboard_stats.active IS 'Current active user count.';
COMMENT ON COLUMN users.dashboard_stats.inactive IS 'Current inactive user count.';
COMMENT ON COLUMN users.dashboard_stats.refreshed_at IS 'Time the projection was rebuilt.';

CREATE MATERIALIZED VIEW users.registration_daily AS
SELECT date_trunc('day', created_at)::date AS day, COUNT(*) AS count
FROM users.users
WHERE deleted_at IS NULL
GROUP BY date_trunc('day', created_at)::date;
CREATE UNIQUE INDEX registration_daily_day_unique ON users.registration_daily (day);
COMMENT ON COLUMN users.registration_daily.day IS 'UTC registration calendar day.';
COMMENT ON COLUMN users.registration_daily.count IS 'Registrations observed on the day.';
