-- users service owns the whole identity record: credentials, status and the
-- profile fields live in ONE table so the dashboard can query them without
-- cross-service joins. auth schema keeps only sessions.
CREATE SCHEMA IF NOT EXISTS users;

CREATE TABLE IF NOT EXISTS users.users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                 TEXT        NOT NULL,
    password_hash         TEXT        NOT NULL,
    status                TEXT        NOT NULL DEFAULT 'active',
    failed_login_attempts INT         NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,
    display_name          TEXT        NOT NULL DEFAULT '',
    avatar_url            TEXT        NOT NULL DEFAULT '',
    last_login_at         TIMESTAMPTZ,
    last_login_ip         TEXT        NOT NULL DEFAULT '',
    last_login_user_agent TEXT        NOT NULL DEFAULT '',
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON users.users (lower(email));
