CREATE SCHEMA IF NOT EXISTS rbac;


CREATE TABLE rbac.roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL UNIQUE,
    description TEXT        NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE rbac.permissions (
    id   BIGSERIAL PRIMARY KEY,
    name TEXT      NOT NULL UNIQUE
);

CREATE TABLE rbac.role_permissions (
    role_id       BIGINT NOT NULL REFERENCES rbac.roles (id) ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES rbac.permissions (id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE rbac.user_roles (
    user_id BIGINT PRIMARY KEY,
    role_id BIGINT NOT NULL REFERENCES rbac.roles (id) ON DELETE CASCADE,
    ver     BIGINT NOT NULL DEFAULT 0
);
