-- rollback: services/rbac/migrations/000005_data_governance.down.sql
SET lock_timeout = '5s';
SET statement_timeout = '5min';

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'rbac.roles'::regclass AND conname = 'roles_name_key') THEN
        ALTER TABLE rbac.roles RENAME CONSTRAINT roles_name_key TO uq_roles_name;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'rbac.permissions'::regclass AND conname = 'permissions_name_key') THEN
        ALTER TABLE rbac.permissions RENAME CONSTRAINT permissions_name_key TO uq_permissions_name;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'rbac.role_permissions'::regclass AND conname = 'role_permissions_role_id_fkey') THEN
        ALTER TABLE rbac.role_permissions RENAME CONSTRAINT role_permissions_role_id_fkey TO fk_role_permissions_role;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'rbac.role_permissions'::regclass AND conname = 'role_permissions_permission_id_fkey') THEN
        ALTER TABLE rbac.role_permissions RENAME CONSTRAINT role_permissions_permission_id_fkey TO fk_role_permissions_permission;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'rbac.user_roles'::regclass AND conname = 'user_roles_role_id_fkey') THEN
        ALTER TABLE rbac.user_roles RENAME CONSTRAINT user_roles_role_id_fkey TO fk_user_roles_role;
    END IF;
END $$;

ALTER TABLE rbac.roles
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS created_by BIGINT,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT,
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD CONSTRAINT ck_roles_name CHECK (name ~ '^[a-z][a-z0-9_-]{1,59}$'),
    ADD CONSTRAINT ck_roles_color CHECK (color ~ '^#[0-9A-Fa-f]{6}$');

ALTER TABLE rbac.permissions
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS created_by BIGINT,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT,
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD CONSTRAINT ck_permissions_name CHECK (name ~ '^[a-z0-9_]+:[a-z0-9_]+:[a-z0-9_]+$');

CREATE OR REPLACE FUNCTION rbac.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_roles_updated_at BEFORE UPDATE ON rbac.roles
FOR EACH ROW EXECUTE FUNCTION rbac.set_updated_at();
CREATE TRIGGER trg_permissions_updated_at BEFORE UPDATE ON rbac.permissions
FOR EACH ROW EXECUTE FUNCTION rbac.set_updated_at();

CREATE TABLE rbac.change_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  TEXT NOT NULL,
    operation   TEXT NOT NULL,
    row_id      TEXT NOT NULL DEFAULT '',
    old_data    JSONB,
    new_data    JSONB,
    changed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    changed_by  BIGINT,
    CONSTRAINT ck_rbac_change_log_operation CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE OR REPLACE FUNCTION rbac.capture_row_change()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO rbac.change_log (table_name, operation, row_id, old_data, new_data, changed_by)
    VALUES (
        TG_TABLE_NAME,
        TG_OP,
        CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END::text,
        CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) END,
        CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) END,
        CASE WHEN TG_OP = 'DELETE' THEN OLD.updated_by ELSE NEW.updated_by END
    );
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_roles_change_log AFTER INSERT OR UPDATE OR DELETE ON rbac.roles
FOR EACH ROW EXECUTE FUNCTION rbac.capture_row_change();
CREATE TRIGGER trg_permissions_change_log AFTER INSERT OR UPDATE OR DELETE ON rbac.permissions
FOR EACH ROW EXECUTE FUNCTION rbac.capture_row_change();

ALTER SEQUENCE rbac.roles_id_seq CACHE 32;
ALTER SEQUENCE rbac.permissions_id_seq CACHE 32;
ALTER SEQUENCE rbac.change_log_id_seq CACHE 32;

COMMENT ON TABLE rbac.roles IS 'Named permission bundle assignable to users.';
COMMENT ON COLUMN rbac.roles.id IS 'Database-generated role identifier.';
COMMENT ON COLUMN rbac.roles.name IS 'Stable lowercase role key.';
COMMENT ON COLUMN rbac.roles.description IS 'Human-readable role purpose.';
COMMENT ON COLUMN rbac.roles.created_at IS 'Database-assigned creation timestamp.';
COMMENT ON COLUMN rbac.roles.color IS 'Six-digit hexadecimal presentation color.';
COMMENT ON COLUMN rbac.roles.icon IS 'Stable presentation icon key.';
COMMENT ON COLUMN rbac.roles.archived IS 'Archived roles remain readable but are not assignable.';
COMMENT ON COLUMN rbac.roles.created_by IS 'Optional actor user id; intentionally no cross-service FK.';
COMMENT ON COLUMN rbac.roles.updated_by IS 'Optional actor user id; intentionally no cross-service FK.';
COMMENT ON COLUMN rbac.roles.updated_at IS 'Database-maintained last modification timestamp.';
COMMENT ON COLUMN rbac.roles.metadata IS 'Non-sensitive extensible role metadata.';
COMMENT ON TABLE rbac.permissions IS 'Canonical fine-grained permission catalog.';
COMMENT ON COLUMN rbac.permissions.id IS 'Database-generated permission identifier.';
COMMENT ON COLUMN rbac.permissions.name IS 'Permission key in resource:action:scope form.';
COMMENT ON COLUMN rbac.permissions.created_at IS 'Database-assigned creation timestamp.';
COMMENT ON COLUMN rbac.permissions.updated_at IS 'Database-maintained last modification timestamp.';
COMMENT ON COLUMN rbac.permissions.created_by IS 'Optional actor user id; intentionally no cross-service FK.';
COMMENT ON COLUMN rbac.permissions.updated_by IS 'Optional actor user id; intentionally no cross-service FK.';
COMMENT ON COLUMN rbac.permissions.metadata IS 'Non-sensitive extensible permission metadata.';
COMMENT ON TABLE rbac.role_permissions IS 'Many-to-many role and permission assignments.';
COMMENT ON COLUMN rbac.role_permissions.role_id IS 'Role reference with cascading delete.';
COMMENT ON COLUMN rbac.role_permissions.permission_id IS 'Permission reference with cascading delete.';
COMMENT ON TABLE rbac.user_roles IS 'Logical user-to-role assignment; user_id has no cross-service FK by design.';
COMMENT ON COLUMN rbac.user_roles.user_id IS 'Logical users.users.id; intentionally no cross-service FK.';
COMMENT ON COLUMN rbac.user_roles.role_id IS 'Assigned role reference with cascading delete.';
COMMENT ON COLUMN rbac.user_roles.ver IS 'Claims version at assignment time.';
COMMENT ON TABLE rbac.user_versions IS 'Monotonic per-user claims invalidation version.';
COMMENT ON COLUMN rbac.user_versions.user_id IS 'Logical users.users.id; intentionally no cross-service FK.';
COMMENT ON COLUMN rbac.user_versions.ver IS 'Monotonic claims version.';
COMMENT ON TABLE rbac.change_log IS 'Database-level row-change history for mutable RBAC catalog rows.';
COMMENT ON COLUMN rbac.change_log.id IS 'Database-generated audit sequence.';
COMMENT ON COLUMN rbac.change_log.table_name IS 'Changed table within the rbac schema.';
COMMENT ON COLUMN rbac.change_log.operation IS 'INSERT, UPDATE, or DELETE.';
COMMENT ON COLUMN rbac.change_log.row_id IS 'Text representation of the changed primary key.';
COMMENT ON COLUMN rbac.change_log.old_data IS 'Pre-change row JSON.';
COMMENT ON COLUMN rbac.change_log.new_data IS 'Post-change row JSON.';
COMMENT ON COLUMN rbac.change_log.changed_at IS 'Database timestamp of the mutation.';
COMMENT ON COLUMN rbac.change_log.changed_by IS 'Optional logical user id responsible for the mutation.';
