// Generated by scripts/generate-contract-modules.mjs.
import type { paths } from "./gen";

export type AuthPaths = Pick<
  paths,
  | "/api/v1/auth/confirm-password"
  | "/api/v1/auth/forgot"
  | "/api/v1/auth/login"
  | "/api/v1/auth/logout"
  | "/api/v1/auth/mfa/enroll"
  | "/api/v1/auth/mfa/verify"
  | "/api/v1/auth/password"
  | "/api/v1/auth/refresh"
  | "/api/v1/auth/register"
  | "/api/v1/auth/reset"
  | "/api/v1/auth/reset/validate"
  | "/api/v1/auth/sessions"
  | "/api/v1/auth/sessions/{id}"
  | "/api/v1/auth/users/{id}/password"
  | "/api/v1/auth/users/{id}/sessions"
  | "/api/v1/auth/users/{id}/sessions/{sessionId}"
  | "/api/v1/auth/users/{id}/state"
>;
