// Generated by scripts/generate-contract-modules.mjs.
import type { paths } from "./gen";

export type RbacPaths = Pick<
  paths,
  | "/api/v1/rbac/internal/claims/{sub}"
  | "/api/v1/rbac/permissions"
  | "/api/v1/rbac/permissions/bulk"
  | "/api/v1/rbac/permissions/{name}"
  | "/api/v1/rbac/roles"
  | "/api/v1/rbac/roles/{id}"
  | "/api/v1/rbac/roles/{id}/users"
  | "/api/v1/rbac/users/{id}/roles"
>;
