// Generated by scripts/generate-contract-modules.mjs.
import { z } from "zod";

export const registerSchema = z
  .object({
    email: z.string().email().max(254),
    password: z.string().min(12).max(72),
    displayName: z.string().max(120).optional(),
  })
  .strict();

export const loginSchema = z
  .object({
    email: z.string().email().max(254),
    password: z.string().max(72),
    otp: z
      .string()
      .max(6)
      .regex(/^[0-9]{6}$/)
      .optional(),
  })
  .strict();

export const verifyMFASchema = z
  .object({
    code: z
      .string()
      .max(6)
      .regex(/^[0-9]{6}$/),
  })
  .strict();

export const forgotPasswordSchema = z
  .object({
    email: z.string().email().max(254),
  })
  .strict();

export const resetPasswordSchema = z
  .object({
    token: z.string().max(4096),
    newPassword: z.string().min(12).max(72),
  })
  .strict();

export const validateResetTokenSchema = z
  .object({
    token: z.string().max(4096),
  })
  .strict();

export const adminSetUserPasswordSchema = z
  .object({
    newPassword: z.string().min(12).max(72),
  })
  .strict();

export const confirmPasswordSchema = z
  .object({
    password: z.string().min(1).max(72),
  })
  .strict();

export const changePasswordSchema = z
  .object({
    oldPassword: z.string().min(1).max(72),
    newPassword: z.string().min(12).max(72),
  })
  .strict();

export const adminSetUserStateSchema = z
  .object({
    status: z.enum(["active", "inactive"]).optional(),
    locked: z.boolean().optional(),
  })
  .strict();

export const createPermissionSchema = z
  .object({
    name: z
      .string()
      .min(5)
      .max(120)
      .regex(/^[a-z0-9_]+:[a-z0-9_]+:[a-z0-9_]+$/),
  })
  .strict();

export const bulkCreatePermissionsSchema = z
  .object({
    names: z
      .array(
        z
          .string()
          .min(5)
          .max(120)
          .regex(/^[a-z0-9_]+:[a-z0-9_]+:[a-z0-9_]+$/),
      )
      .min(1)
      .max(100),
  })
  .strict();

export const createRoleSchema = z
  .object({
    name: z.string().min(2).max(60),
    description: z.string().max(300).optional(),
    color: z
      .string()
      .max(7)
      .regex(/^#[0-9a-fA-F]{6}$/)
      .optional(),
    icon: z.string().max(60).optional(),
    archived: z.boolean().optional(),
    permissions: z.array(z.string().max(120)).max(200).optional(),
  })
  .strict();

export const updateRoleSchema = z.intersection(
  z
    .object({
      name: z.string().min(2).max(60),
      description: z.string().max(300).optional(),
      color: z
        .string()
        .max(7)
        .regex(/^#[0-9a-fA-F]{6}$/)
        .optional(),
      icon: z.string().max(60).optional(),
      archived: z.boolean().optional(),
      permissions: z.array(z.string().max(120)).max(200).optional(),
    })
    .strict(),
  z
    .object({
      permissions: z.array(z.string().max(120)).max(200).optional(),
    })
    .strict(),
);

export const setUserRolesSchema = z
  .object({
    roleIds: z.array(z.number().int()).max(100),
  })
  .strict();

export const createUserProfileSchema = z
  .object({
    id: z.number().int(),
    email: z.string().email().max(254).optional(),
    displayName: z.string().max(120).optional(),
    avatarUrl: z
      .string()
      .max(400)
      .regex(/^$|^https:\/\//)
      .optional(),
  })
  .strict();

export const updateUserSchema = z
  .object({
    email: z.string().email().max(254).optional(),
    displayName: z.string().max(120).optional(),
    avatarUrl: z
      .string()
      .max(400)
      .regex(/^$|^https:\/\//)
      .optional(),
  })
  .strict();
