// Generated by scripts/generate-contract-modules.mjs.
import { z } from "zod";

export const registerSchema = z
  .object({
    email: z.string().email().max(254),
    password: z.string().min(12).max(72),
    displayName: z.string().max(120).optional(),
  })
  .strict();

export const loginSchema = z
  .object({
    email: z.string().email().max(254),
    password: z.string().max(72),
    otp: z.string().min(6).max(64).optional(),
  })
  .strict();

export const verifyMFASchema = z
  .object({
    code: z
      .string()
      .max(6)
      .regex(/^[0-9]{6}$/),
  })
  .strict();

export const requestMagicLinkSchema = z
  .object({
    email: z.string().email().max(254),
  })
  .strict();

export const consumeMagicLinkSchema = z
  .object({
    token: z.string().max(4096),
  })
  .strict();

export const forgotPasswordSchema = z
  .object({
    email: z.string().email().max(254),
  })
  .strict();

export const resetPasswordSchema = z
  .object({
    token: z.string().max(4096),
    newPassword: z.string().min(12).max(72),
  })
  .strict();

export const validateResetTokenSchema = z
  .object({
    token: z.string().max(4096),
  })
  .strict();

export const adminSetUserPasswordSchema = z
  .object({
    newPassword: z.string().min(12).max(72),
  })
  .strict();

export const confirmPasswordSchema = z
  .object({
    password: z.string().min(1).max(72),
  })
  .strict();

export const changePasswordSchema = z
  .object({
    oldPassword: z.string().min(1).max(72),
    newPassword: z.string().min(12).max(72),
  })
  .strict();

export const adminSetUserStateSchema = z
  .object({
    status: z.enum(["active", "inactive"]).optional(),
    locked: z.boolean().optional(),
  })
  .strict();

export const createPermissionSchema = z
  .object({
    name: z
      .string()
      .min(5)
      .max(120)
      .regex(/^[a-z0-9_]+:[a-z0-9_]+:[a-z0-9_]+$/),
  })
  .strict();

export const bulkCreatePermissionsSchema = z
  .object({
    names: z
      .array(
        z
          .string()
          .min(5)
          .max(120)
          .regex(/^[a-z0-9_]+:[a-z0-9_]+:[a-z0-9_]+$/),
      )
      .min(1)
      .max(100),
  })
  .strict();

export const createRoleSchema = z
  .object({
    name: z.string().min(2).max(60),
    description: z.string().max(300).optional(),
    color: z
      .string()
      .max(7)
      .regex(/^#[0-9a-fA-F]{6}$/)
      .optional(),
    icon: z.string().max(60).optional(),
    archived: z.boolean().optional(),
    permissions: z.array(z.string().max(120)).max(200).optional(),
  })
  .strict();

export const updateRoleSchema = z.intersection(
  z
    .object({
      name: z.string().min(2).max(60),
      description: z.string().max(300).optional(),
      color: z
        .string()
        .max(7)
        .regex(/^#[0-9a-fA-F]{6}$/)
        .optional(),
      icon: z.string().max(60).optional(),
      archived: z.boolean().optional(),
      permissions: z.array(z.string().max(120)).max(200).optional(),
    })
    .strict(),
  z
    .object({
      permissions: z.array(z.string().max(120)).max(200).optional(),
    })
    .strict(),
);

export const setUserRolesSchema = z
  .object({
    roleIds: z.array(z.number().int()).max(100),
  })
  .strict();

export const createUserProfileSchema = z
  .object({
    id: z.number().int(),
    email: z.string().email().max(254).optional(),
    displayName: z.string().max(120).optional(),
    avatarUrl: z
      .string()
      .max(400)
      .regex(/^$|^https:\/\//)
      .optional(),
  })
  .strict();

export const createProductRecordSchema = z
  .object({
    kind: z.enum([
      "notification",
      "invitation",
      "access_request",
      "delegation",
      "api_key",
      "webhook",
      "scheduled_report",
      "saved_view",
      "role_template",
      "compliance_report",
      "branding",
      "domain",
      "billing_usage",
      "broadcast",
      "chat_message",
      "onboarding",
      "retention",
      "consumer_quota",
      "email_change",
      "account_deletion",
    ]),
    subjectId: z.number().int().min(1).optional(),
    name: z.string().min(1).max(200),
    status: z.string().max(40).optional(),
    payload: z.object({}).strict(),
    expiresAt: z.string().nullable().optional(),
  })
  .strict();

export const updateProductRecordSchema = z
  .object({
    status: z.string().min(1).max(40),
    payload: z.object({}).strict(),
  })
  .strict();

export const simulatePermissionSchema = z
  .object({
    userId: z.number().int().min(1),
    permission: z.string().min(1).max(120),
  })
  .strict();

export const verifyInvitationSchema = z
  .object({
    token: z.string().min(20).max(512),
  })
  .strict();

export const requestEmailChangeSchema = z
  .object({
    email: z.string().email().max(254),
  })
  .strict();

export const verifyEmailChangeSchema = z
  .object({
    token: z.string().min(20).max(512),
  })
  .strict();

export const restoreAccountDeletionSchema = z
  .object({
    token: z.string().min(20).max(512),
  })
  .strict();

export const updateUserSchema = z
  .object({
    email: z.string().email().max(254).optional(),
    displayName: z.string().max(120).optional(),
    avatarUrl: z
      .string()
      .max(400)
      .regex(/^$|^https:\/\//)
      .optional(),
  })
  .strict();
