// Generated by scripts/generate-contract-modules.mjs.
import type { paths } from "./gen";

export type UsersPaths = Pick<
  paths,
  | "/api/v1/users"
  | "/api/v1/users/avatar/resize"
  | "/api/v1/users/deletion/restore"
  | "/api/v1/users/email-change/verify"
  | "/api/v1/users/me"
  | "/api/v1/users/me/deletion"
  | "/api/v1/users/me/email-change"
  | "/api/v1/users/me/export"
  | "/api/v1/users/product/analytics"
  | "/api/v1/users/product/invitations/verify"
  | "/api/v1/users/product/overview"
  | "/api/v1/users/product/permissions/simulate"
  | "/api/v1/users/product/presence"
  | "/api/v1/users/product/records"
  | "/api/v1/users/product/records/{id}"
  | "/api/v1/users/product/search"
  | "/api/v1/users/stats"
  | "/api/v1/users/{id}"
>;
