// Generated by scripts/generate-contract-modules.mjs.
import type { paths } from "./gen";

export type UsersPaths = Pick<
  paths,
  | "/api/v1/users"
  | "/api/v1/users/avatar/resize"
  | "/api/v1/users/me"
  | "/api/v1/users/me/export"
  | "/api/v1/users/stats"
  | "/api/v1/users/{id}"
>;
