apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-admin-roles
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-admin-roles
  template:
    metadata:
      labels:
        app: web-admin-roles
    spec:
      containers:
        - name: nginx
          image: ghcr.io/kochan4php/web-admin-roles:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 10
