root = "."
tmp_dir = "tmp/air/_template"

[build]
cmd = "go build -o ./tmp/air/_template/app ./services/_template"
bin = "./tmp/air/_template/app"
full_bin = "APP_ENV_FILE=services/_template/.env ./tmp/air/_template/app"
include_ext = ["go", "sql", "yaml", "yml", "env"]
exclude_dir = [".git", "graphify-out", "node_modules", "tmp"]
delay = 300
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true
