// Docusaurus renders the repository's existing docs/ tree in place. The files
// stay where scripts/generate-docs.mjs, scripts/check-docs.mjs and the other
// generators expect them; only the rendering lives here.
//
// Publishing requires the repository's Pages source to be "GitHub Actions".
// With Pages set to "Deploy from a branch" the workflow's deploy step fails
// with a 404 and GitHub serves the raw Markdown instead.

const organizationName = "kochan4php";
const projectName = "go-platform-starter";

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "go-platform-starter",
  tagline: "Go microservices, a federated React shell, and spec-first contracts",
  favicon: "img/favicon.svg",

  url: `https://${organizationName}.github.io`,
  baseUrl: `/${projectName}/`,
  organizationName,
  projectName,

  // A broken internal link is a defect, not a warning: scripts/check-docs.mjs
  // already guarantees every link resolves to a real file.
  onBrokenLinks: "throw",

  markdown: {
    // "detect" parses .md as CommonMark and reserves MDX for .mdx. Without it
    // Docusaurus 3 treats every .md file as MDX, and these pages are full of
    // ${SHELL_VARS} and <angle brackets> that MDX rejects as broken JSX.
    format: "detect",
    hooks: { onBrokenMarkdownLinks: "throw" },
  },

  i18n: { defaultLocale: "en", locales: ["en"] },

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          path: "../docs",
          routeBasePath: "/",
          sidebarPath: "./sidebars.js",
          // ADR filenames start with their number (0001-fresh-build-pivot).
          // Docusaurus reads a leading number as an ordering prefix and strips
          // it from the document id, which would rename every ADR.
          numberPrefixParser: false,
          editUrl: `https://github.com/${organizationName}/${projectName}/edit/main/`,
          showLastUpdateTime: true,
          exclude: ["BACKLOG.md", "archive/**", "testing/**", "assets/**", "**/_*.md", "**/node_modules/**"],
        },
        blog: false,
        theme: { customCss: "./src/css/custom.css" },
        sitemap: { changefreq: "weekly", priority: 0.5 },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: { defaultMode: "light", respectPrefersColorScheme: true },
      navbar: {
        title: "go-platform-starter",
        items: [
          { type: "docSidebar", sidebarId: "docs", position: "left", label: "Documentation" },
          {
            href: `https://github.com/${organizationName}/${projectName}`,
            label: "GitHub",
            position: "right",
          },
        ],
      },
      footer: {
        style: "dark",
        links: [
          {
            title: "Start",
            items: [
              { label: "Onboarding", to: "/ONBOARDING" },
              { label: "Architecture", to: "/ARCHITECTURE" },
              { label: "Engineering guide", to: "/ENGINEERING_GUIDE" },
            ],
          },
          {
            title: "Operate",
            items: [
              { label: "Runbook", to: "/RUNBOOK" },
              { label: "On-call", to: "/ONCALL" },
              { label: "Security posture", to: "/SECURITY" },
            ],
          },
          {
            title: "Repository",
            items: [
              { label: "GitHub", href: `https://github.com/${organizationName}/${projectName}` },
              {
                label: "Contributing",
                href: `https://github.com/${organizationName}/${projectName}/blob/main/CONTRIBUTING.md`,
              },
            ],
          },
        ],
        copyright:
          "Pages under reference/ are generated by scripts/generate-docs.mjs — edit the source, not the page.",
      },
      prism: {
        additionalLanguages: ["bash", "go", "sql", "yaml", "json", "docker"],
      },
    }),

  plugins: [
    [
      "@easyops-cn/docusaurus-search-local",
      /** @type {import('@easyops-cn/docusaurus-search-local').PluginOptions} */
      // docsDir must point at the real tree; the plugin defaults to
      // website/docs and silently indexes nothing when that is missing.
      ({ hashed: true, indexBlog: false, docsDir: "../docs", docsRouteBasePath: "/" }),
    ],
  ],
};

export default config;
