-- auth keeps ONLY session state. The identity row lives in users.users
-- (owned by the users service); sessions reference it by numeric id without a
-- cross-service foreign key so migration order never matters.
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.sessions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL,
    refresh_token_hash TEXT        NOT NULL UNIQUE,
    family_id          TEXT        NOT NULL,
    user_agent         TEXT        NOT NULL DEFAULT '',
    ip                 TEXT        NOT NULL DEFAULT '',
    expires_at         TIMESTAMPTZ NOT NULL,
    revoked_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sessions_user_idx ON auth.sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_family_idx ON auth.sessions (family_id);
