SET lock_timeout = '5s';
SET statement_timeout = '5min';

CREATE TABLE IF NOT EXISTS auth.login_events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    success     BOOLEAN     NOT NULL,
    risk_score  SMALLINT    NOT NULL DEFAULT 0 CHECK (risk_score BETWEEN 0 AND 100),
    anomalous   BOOLEAN     NOT NULL DEFAULT false,
    ip          TEXT        NOT NULL DEFAULT '',
    user_agent  TEXT        NOT NULL DEFAULT '',
    reason      TEXT        NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS login_events_user_created_idx
    ON auth.login_events (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS login_events_anomaly_created_idx
    ON auth.login_events (created_at DESC)
    WHERE anomalous;

CREATE TABLE IF NOT EXISTS auth.identity_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT,
    kind         TEXT        NOT NULL CHECK (kind IN ('recovery_code', 'magic_link', 'oauth_state')),
    token_digest TEXT        NOT NULL UNIQUE,
    payload      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    expires_at   TIMESTAMPTZ NOT NULL,
    consumed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT identity_tokens_payload_size CHECK (pg_column_size(payload) <= 16384)
);

CREATE INDEX IF NOT EXISTS identity_tokens_user_kind_active_idx
    ON auth.identity_tokens (user_id, kind, expires_at)
    WHERE consumed_at IS NULL;

COMMENT ON TABLE auth.login_events IS
    'Privacy-bounded authentication history with deterministic, explainable risk scoring.';
COMMENT ON TABLE auth.identity_tokens IS
    'Single-use authentication grants; plaintext tokens are never persisted.';
