-- 000002_integer_ids: convert identity columns from UUID to BIGINT
-- GENERATED BY DEFAULT AS IDENTITY (see docs/MIGRATIONS.md).
--
-- One-time breaking reset for pre-release environments: UUID values cannot be
-- converted to integers, so affected tables are dropped and recreated. All
-- rows are re-materialized by the standard seeders on the next deploy.
DROP TABLE IF EXISTS auth.sessions CASCADE;
DROP TABLE IF EXISTS auth.users CASCADE;

CREATE TABLE auth.users (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email                  TEXT        NOT NULL,
    password_hash          TEXT        NOT NULL,
    status                 TEXT        NOT NULL DEFAULT 'active',
    failed_login_attempts  INT         NOT NULL DEFAULT 0,
    locked_until           TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_unique ON auth.users (lower(email));

CREATE TABLE auth.sessions (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT      NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
    refresh_token_hash TEXT        NOT NULL UNIQUE,
    family_id          TEXT        NOT NULL,
    user_agent         TEXT        NOT NULL DEFAULT '',
    ip                 TEXT        NOT NULL DEFAULT '',
    expires_at         TIMESTAMPTZ NOT NULL,
    revoked_at         TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS sessions_user_idx ON auth.sessions (user_id);
CREATE INDEX IF NOT EXISTS sessions_family_idx ON auth.sessions (family_id);
