-- rollback: services/auth/migrations/000004_data_governance.down.sql
SET lock_timeout = '5s';
SET statement_timeout = '5min';

ALTER TABLE auth.sessions
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS created_by BIGINT,
    ADD COLUMN IF NOT EXISTS updated_by BIGINT,
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'auth.sessions'::regclass
          AND conname = 'sessions_refresh_token_hash_key'
    ) THEN
        ALTER TABLE auth.sessions
            RENAME CONSTRAINT sessions_refresh_token_hash_key TO uq_sessions_refresh_token_hash;
    END IF;
END $$;

ALTER TABLE auth.sessions
    ADD CONSTRAINT ck_sessions_expiry_after_creation CHECK (expires_at > created_at);

CREATE OR REPLACE FUNCTION auth.set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_sessions_updated_at
BEFORE UPDATE ON auth.sessions
FOR EACH ROW EXECUTE FUNCTION auth.set_updated_at();

CREATE TABLE auth.change_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name  TEXT NOT NULL,
    operation   TEXT NOT NULL,
    row_id      TEXT NOT NULL DEFAULT '',
    old_data    JSONB,
    new_data    JSONB,
    changed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    changed_by  BIGINT,
    CONSTRAINT ck_auth_change_log_operation CHECK (operation IN ('INSERT', 'UPDATE', 'DELETE'))
);

CREATE OR REPLACE FUNCTION auth.capture_row_change()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO auth.change_log (table_name, operation, row_id, old_data, new_data, changed_by)
    VALUES (
        TG_TABLE_NAME,
        TG_OP,
        CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END::text,
        CASE WHEN TG_OP IN ('UPDATE', 'DELETE') THEN to_jsonb(OLD) - 'refresh_token_hash' END,
        CASE WHEN TG_OP IN ('INSERT', 'UPDATE') THEN to_jsonb(NEW) - 'refresh_token_hash' END,
        CASE WHEN TG_OP = 'DELETE' THEN OLD.updated_by ELSE NEW.updated_by END
    );
    RETURN NULL;
END;
$$;

CREATE TRIGGER trg_sessions_change_log
AFTER INSERT OR UPDATE OR DELETE ON auth.sessions
FOR EACH ROW EXECUTE FUNCTION auth.capture_row_change();

ALTER SEQUENCE auth.sessions_id_seq CACHE 32;
ALTER SEQUENCE auth.change_log_id_seq CACHE 32;

COMMENT ON TABLE auth.sessions IS 'Refresh-session state owned by the auth service.';
COMMENT ON COLUMN auth.sessions.id IS 'Database-generated session identifier.';
COMMENT ON COLUMN auth.sessions.user_id IS 'Logical users.users.id reference; intentionally no cross-service foreign key.';
COMMENT ON COLUMN auth.sessions.refresh_token_hash IS 'One-way refresh-token digest; never emitted by audit triggers.';
COMMENT ON COLUMN auth.sessions.family_id IS 'Refresh-token rotation family identifier.';
COMMENT ON COLUMN auth.sessions.user_agent IS 'Last observed client user-agent string.';
COMMENT ON COLUMN auth.sessions.ip IS 'Last observed client IP text representation.';
COMMENT ON COLUMN auth.sessions.expires_at IS 'Absolute refresh-session expiry.';
COMMENT ON COLUMN auth.sessions.revoked_at IS 'Revocation timestamp; null while active.';
COMMENT ON COLUMN auth.sessions.created_at IS 'Database-assigned session creation timestamp.';
COMMENT ON COLUMN auth.sessions.device_id IS 'Stable client-generated device identifier when available.';
COMMENT ON COLUMN auth.sessions.metadata IS 'Non-sensitive session attributes for operational enrichment.';
COMMENT ON COLUMN auth.sessions.created_by IS 'Optional actor user id; no FK to preserve service migration independence.';
COMMENT ON COLUMN auth.sessions.updated_by IS 'Optional actor user id; no FK to preserve service migration independence.';
COMMENT ON COLUMN auth.sessions.updated_at IS 'Database-maintained last modification timestamp.';
COMMENT ON TABLE auth.change_log IS 'Database-level immutable row-change history for auth-owned tables.';
COMMENT ON COLUMN auth.change_log.id IS 'Database-generated audit sequence.';
COMMENT ON COLUMN auth.change_log.table_name IS 'Changed table within the auth schema.';
COMMENT ON COLUMN auth.change_log.operation IS 'INSERT, UPDATE, or DELETE.';
COMMENT ON COLUMN auth.change_log.row_id IS 'Text representation of the changed primary key.';
COMMENT ON COLUMN auth.change_log.old_data IS 'Pre-change JSON with credential material removed.';
COMMENT ON COLUMN auth.change_log.new_data IS 'Post-change JSON with credential material removed.';
COMMENT ON COLUMN auth.change_log.changed_at IS 'Database timestamp of the mutation.';
COMMENT ON COLUMN auth.change_log.changed_by IS 'Optional logical user id responsible for the mutation.';
