// Command composespec merges every service's openapi.yaml (skipping
// _template) into packages/contracts/openapi.json — the static aggregate the
// TS client is generated from (PLAN item 37: frontend builds never need a
// live mesh).
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

func main() {
	root := flag.String("root", ".", "repo root")
	out := flag.String("out", "packages/contracts/openapi.json", "output path")
	flag.Parse()

	servicesDir := filepath.Join(*root, "services")
	entries, err := os.ReadDir(servicesDir)
	if err != nil {
		die("read services dir: %v", err)
	}

	merged := map[string]any{
		"openapi": "3.0.3",
		"info": map[string]any{
			"title":       "platform aggregate API",
			"description": "Generated by cmd/composespec — DO NOT EDIT. Source of truth: services/*/openapi.yaml",
			"version":     "0.1.0",
		},
		"servers":    []map[string]string{{"url": "/"}},
		"paths":      map[string]any{},
		"components": map[string]any{"schemas": map[string]any{}},
	}
	paths := merged["paths"].(map[string]any)
	schemas := merged["components"].(map[string]any)["schemas"].(map[string]any)

	for _, entry := range entries {
		if !entry.IsDir() || entry.Name() == "_template" {
			continue
		}
		specPath := filepath.Join(servicesDir, entry.Name(), "openapi.yaml")
		raw, err := os.ReadFile(specPath)
		if err != nil {
			continue // services without a spec yet are skipped silently
		}
		var doc struct {
			Paths      map[string]any `yaml:"paths"`
			Components struct {
				Schemas map[string]any `yaml:"schemas"`
			} `yaml:"components"`
		}
		if err := yaml.Unmarshal(raw, &doc); err != nil {
			die("parse %s: %v", specPath, err)
		}
		prefix := "/api/v1"
		for p, op := range doc.Paths {
			paths[prefix+p] = op
		}
		for name, sch := range doc.Components.Schemas {
			if _, exists := schemas[name]; !exists {
				schemas[name] = sch
			}
		}
		fmt.Println("merged:", entry.Name())
	}

	outBytes, err := json.MarshalIndent(merged, "", "  ")
	if err != nil {
		die("marshal: %v", err)
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		die("mkdir: %v", err)
	}
	if err := os.WriteFile(*out, append(outBytes, '\n'), 0o644); err != nil {
		die("write: %v", err)
	}
	fmt.Println("wrote", *out, "")
}

func die(format string, a ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", a...)
	os.Exit(1)
}
